### data 

In [1]:
import numpy as np


def load_data(npysplit):
    data = np.load(npysplit)
    return data

data_dir = "/n/projects/kc2819/projects/ChotaLLM/data/wikitext2"
trn_path, val_path, tst_path = data_dir + "/wikitext-2-raw-v1_train_000000.npy", data_dir + "/wikitext-2-raw-v1_validation_000000.npy", data_dir + "/wikitext-2-raw-v1_test_000000.npy"
train_data = load_data(trn_path)
valid_data = load_data(val_path)
test_data = load_data(tst_path)


print(f'number of tokens in train: {len(train_data)/10e6}M')
print(f'number of tokens in valid: {len(valid_data)/10e6}M')
print(f'number of tokens in test: {len(test_data)/10e6}M')

number of tokens in train: 0.1M
number of tokens in valid: 0.0251049M
number of tokens in test: 0.0287645M


In [2]:
train_data[:100], test_data[:100], valid_data[:100]

(array([50256, 50256,   796,   569, 18354,  7496, 17740,  6711,   796,
          220,   198, 50256, 50256,  2311,    73, 13090,   645,   569,
        18354,  7496,   513,  1058,   791, 47398, 17740,   357,  4960,
         1058, 10545,   230,    99,   161,   254,   112,  5641, 44444,
         9202, 25084, 24440, 12675, 11839,    18,   837,  6578,   764,
          569, 18354,  7496,   286,   262, 30193,   513,  1267,   837,
         8811,  6412,   284,   355,   569, 18354,  7496, 17740,  6711,
         2354,  2869,   837,   318,   257, 16106,  2597,  2488,    12,
           31,  2712,  2008,   983,  4166,   416, 29490,   290,  6343,
           13, 44206,   329,   262, 14047, 44685,   764, 28728,   287,
         3269,  2813,   287,  2869,   837,   340,   318,   262,  2368,
          983], dtype=uint16),
 array([50256, 50256,   796,  5199,   347,  2852,   353,   796,   220,
          198, 50256, 50256,  5199,   347,  2852,   353,   318,   281,
         3594,  2646,   837,  5581,   290, 214

In [3]:

import sys
sys.path.append("/n/projects/kc2819/projects/ChotaLLM")

from src.dataUtils import CustomDataset, CustomDataloader, CustomTokenizer

batch_size = 5
block_size = 32
embedding_size = 12

tokenizer = CustomTokenizer()

tokenizer.get_vocab_size()

50257

In [4]:
seq = train_data[:1000]
print(tokenizer.decode_np(seq))

<|endoftext|><|endoftext|> = Valkyria Chronicles III = 
<|endoftext|><|endoftext|> Senjō no Valkyria 3 : Unrecorded Chronicles ( Japanese : 戦場のヴァルキュリア3 , lit . Valkyria of the Battlefield 3 ) , commonly referred to as Valkyria Chronicles III outside Japan , is a tactical role @-@ playing video game developed by Sega and Media.Vision for the PlayStation Portable . Released in January 2011 in Japan , it is the third game in the Valkyria series . Employing the same fusion of tactical and real @-@ time gameplay as its predecessors , the story runs parallel to the first game and follows the " Nameless " , a penal military unit serving the nation of Gallia during the Second Europan War who perform secret black operations and are pitted against the Imperial unit " Calamaty Raven " . 
<|endoftext|> The game began development in 2010 , carrying over a large portion of the work done on Valkyria Chronicles II . While it retained the standard features of the series , it also underwent multiple adj

In [5]:
train_dataset = CustomDataset(trn_path, block_size= block_size)
valid_dataset = CustomDataset(val_path, block_size= block_size)
test_dataset = CustomDataset(tst_path, block_size= block_size)


In [6]:
print(len(train_dataset), len(valid_dataset), len(test_dataset))
print(f'train', train_dataset[0],'\n', f'valid', valid_dataset[0],'\n', f'test', test_dataset[0])

31250 7845 8988
train (tensor([50256, 50256,   796,   569, 18354,  7496, 17740,  6711,   796,   220,
          198, 50256, 50256,  2311,    73, 13090,   645,   569, 18354,  7496,
          513,  1058,   791, 47398, 17740,   357,  4960,  1058, 10545,   230,
           99,   161]), tensor([50256,   796,   569, 18354,  7496, 17740,  6711,   796,   220,   198,
        50256, 50256,  2311,    73, 13090,   645,   569, 18354,  7496,   513,
         1058,   791, 47398, 17740,   357,  4960,  1058, 10545,   230,    99,
          161,   254])) 
 valid (tensor([50256, 50256,   796,  8074, 20272,  9106,  3876,   385,   796,   220,
          198, 50256, 50256,  8074, 20272,  9106,  3876,   385,   837,  1900,
          355,   262,  3427, 43657,   393,  2219, 43657,   837,   318,   257,
         4693,   286]), tensor([50256,   796,  8074, 20272,  9106,  3876,   385,   796,   220,   198,
        50256, 50256,  8074, 20272,  9106,  3876,   385,   837,  1900,   355,
          262,  3427, 43657,   393,  2

In [7]:
# lets test the dataloaders
train_loader = CustomDataloader(train_dataset, batch_size=batch_size, shuffle=True)
valid_loader = CustomDataloader(valid_dataset, batch_size=batch_size, shuffle=True)
test_loader = CustomDataloader(test_dataset, batch_size=batch_size, shuffle=True)



In [8]:
next(iter(train_loader)), next(iter(valid_loader)), next(iter(test_loader))

((tensor([[ 3790,   832,   262,  4960,  3818,   705,    82,  6441,   764,   220,
             198, 50256, 50256,   796,   796,  8495,   796,   796,   220,   198,
           50256, 50256,   383,  5994, 10048, 16790,   318, 12228,   416,   257,
            1180,  9030],
          [10719,   284,   423,  5180,  5780,   837, 16852,   274,   837, 10799,
           27893, 27180,   837,  5045,  6893,   392,   290,  2199,   293,  1511,
             284,  8319,   319,   262,  4205,   837,   290,   423,   257,   366,
           39350,  3420],
          [  290, 11513,   257,  7389,  4829,   284,  1317,   465,   717,  4492,
            5585,   351,   257,  3061,   764,   770,   925,   683,   262, 18887,
            2137,   284,  4776,   319,   465,  4492,  8886,   837,   257,  1700,
             543, 15436],
          [   82,  4075,  2524,   837,   393,   262,  3518,  3814,   286,   262,
            7532,   326, 49567,   287,  5931,  3797,  8767,   764,   554,  4610,
           15568,   635, 17777,

In [9]:

trn_batch = next(iter(train_loader))
print(trn_batch[0].shape, trn_batch[1].shape) # batch_size, block_size

tst_batch = next(iter(test_loader))
print(tst_batch[0].shape, tst_batch[1].shape)

val_batch = next(iter(valid_loader))
print(val_batch[0].shape, val_batch[1].shape)

torch.Size([5, 32]) torch.Size([5, 32])
torch.Size([5, 32]) torch.Size([5, 32])
torch.Size([5, 32]) torch.Size([5, 32])


## Dynamic datasets and dataloader

In [11]:
import os
from torch import tensor, long


def load_tokens(filename):
    npt = np.load(filename)
    npt = npt.astype(np.int32) 
    ptt = tensor(npt, dtype=long)
    return ptt


class DataLoaderLite:

    def __init__(self,B,T,process_rank,num_processes,split, master_process = True):
        self.B = B
        self.T = T
        self.process_rank = process_rank
        self.num_processes = num_processes
        assert split in ['train','valid','test'], "split should be either train, valid or test"
         
        data_root = '/n/projects/kc2819/projects/ChotaLLM/data/wikitext2'
        shards = os.listdir(data_root)

        shards = [ shard for shard in shards if shard.endswith('.npy')]

        shards = [s for s in shards if split in s]
        shards = sorted(shards)
        shards = [os.path.join(data_root,s) for s in shards]
        self.shards = shards

        assert len(self.shards) > 0, "No shards found in the data directory"

        if master_process:
            print(f"Found {len(self.shards)} shards for {split} split")

        self.reset()

    # what happens when we reset the dataloader
    # when we reset the dataloader, we reset the current shard to 0, that means we start from the first shard in the list and tokens are loaded from the first shard in the list
    # the current position is set to B * T * process_rank, that means we start from the beginning of the shard and the tokens are loaded from the beginning of the shard
        
    # if the process rank is 0, then the current position is 0, if the process rank is 1, then the current position is B * T, if the process rank is 2, then the current position is 2 * B * T and so on
    # this is done to ensure that the data is loaded in a distributed manner, that is each process loads a different part of the data
    # the tokens are loaded from the current position to the current position + B * T + 1, that is we load B * T tokens for the inputs and B * T tokens for the targets
        
    # this is okay if the tokens are in one big array, but if the tokens are in multiple shards, then we need to load the tokens from the current shard
    # if the current position + B * T * num_processes + 1 is greater than the length of the tokens, then we move to the next shard
    # we set the current shard to the next shard, and load the tokens from the next shard
        
        

    def reset(self):
        self.current_shard = 0
        self.tokens = load_tokens(self.shards[self.current_shard])
        print(len(self.tokens))
        self.current_position = self.B * self.T * self.process_rank

    def next_batch(self):
        B,T = self.B, self.T
        buf = self.tokens[self.current_position:self.current_position + B*T + 1]
        print(len(buf), len(self.tokens), len(self.tokens) - self.current_position, len(self.tokens) - len(buf))
        x = (buf[:-1]).view(B, T) # inputs
        y = (buf[1:]).view(B, T) # targets

        self.current_position += B * T * self.num_processes
        if self.current_position + (B * T * self.num_processes + 1) > len(self.tokens):
            self.current_shard = (self.current_shard + 1) % len(self.shards)
            self.tokens = load_tokens(self.shards[self.current_shard])
            self.current_position = B * T * self.process_rank
        return x, y # B x T

In [12]:
batch_size = 100
block_size = 450
dataloder = DataLoaderLite(B=batch_size, T=block_size, process_rank=2, num_processes=2, split='train')

Found 3 shards for train split
1000000


In [13]:
x, y = dataloder.next_batch()
dataloder.current_position, dataloder.current_shard

45001 1000000 910000 954999


(180000, 0)

In [14]:
x.shape, y.shape

(torch.Size([100, 450]), torch.Size([100, 450]))

In [15]:
import os
import numpy as np
import torch
from torch import tensor, stack, long
from torch.nn.utils.rnn import pad_sequence
from torch.utils.data import Dataset, DataLoader, DistributedSampler

In [21]:
class ShardDataset(Dataset):
    def __init__(self, data_dir, block_size=128, file_extension='.npy', split='train', process_rank=0, num_processes=1):
        self.data_dir = data_dir
        self.block_size = block_size
        self.file_extension = file_extension
        self.split = split
        self.process_rank = process_rank
        self.num_processes = num_processes
        self.shards = self._load_shards()
        self.current_shard_idx = process_rank
        self.data = self._load_data()

        self._cached_len = 0

    def _load_shards(self):
        shards = [os.path.join(self.data_dir, f) for f in os.listdir(self.data_dir) if f.endswith(self.file_extension) and self.split in f]
        shards.sort()
        assert len(shards) > 0, f"No shards found in directory {self.data_dir} for split {self.split}."
        return shards

    def _load_data(self):
        data = np.load(self.shards[self.current_shard_idx])
        if data.dtype == np.int16:
            data = data.astype(np.int32)
        data = tensor(data, dtype=long)
        return data

    def _next_shard(self):
        self.current_shard_idx = (self.current_shard_idx + self.num_processes) % len(self.shards)
        self.data = self._load_data()
    
    def __len__(self):
        if not hasattr(self, '_cached_len'):
            self._cached_len = sum(len(np.load(shard)) for shard in self.shards) // (self.block_size * self.num_processes)
        return self._cached_len


    def __getitem__(self, idx):
        local_idx = idx % (len(self.data) // self.block_size)
        start_idx = local_idx * self.block_size
        end_idx = start_idx + self.block_size if start_idx + self.block_size < len(self.data) else len(self.data)
        inputs_ids = self.data[start_idx:end_idx]
        labels = self.data[start_idx + 1:end_idx + 1]

        if len(labels) < self.block_size:
            labels = torch.cat((labels, self.data[:self.block_size - len(labels)]))

        if local_idx == (len(self.data) // self.block_size) - 1:
            self._next_shard()

        return inputs_ids, labels

In [22]:
dataset = ShardDataset(data_dir, block_size=block_size, split='train', process_rank=0, num_processes=2)

In [23]:
len(dataset)

0

In [24]:
class ShardDataset(Dataset):
    def __init__(self, data_dir, block_size=128, file_extension='.npy', split='train', process_rank=0, num_processes=1):
        self.data_dir = data_dir
        self.block_size = block_size
        self.file_extension = file_extension
        self.split = split
        self.process_rank = process_rank
        self.num_processes = num_processes
        self.shards = self._load_shards()
        self.current_shard_idx = process_rank
        self.data = self._load_data()

        self._cached_len = None  # Use None for lazy length calculation

    def _load_shards(self):
        shards = [os.path.join(self.data_dir, f) for f in os.listdir(self.data_dir) if f.endswith(self.file_extension) and self.split in f]
        shards.sort()
        assert len(shards) > 0, f"No shards found in directory {self.data_dir} for split {self.split}."
        return shards

    def _load_data(self):
        data = np.load(self.shards[self.current_shard_idx])
        if data.dtype == np.int16:
            data = data.astype(np.int32)
        data = tensor(data, dtype=long)
        return data

    def _next_shard(self):
        self.current_shard_idx = (self.current_shard_idx + self.num_processes) % len(self.shards)
        self.data = self._load_data()

    def __len__(self):
        if self._cached_len is None:
            self._cached_len = sum(len(np.load(shard)) for shard in self.shards) // (self.block_size * self.num_processes)
        return self._cached_len

    def __getitem__(self, idx):
        local_idx = idx % (len(self.data) // self.block_size)
        start_idx = local_idx * self.block_size
        end_idx = start_idx + self.block_size if start_idx + self.block_size < len(self.data) else len(self.data)
        inputs_ids = self.data[start_idx:end_idx]
        labels = self.data[start_idx + 1:end_idx + 1]

        if len(labels) < self.block_size:
            next_data = self.data[:self.block_size - len(labels)] if local_idx != (len(self.data) // self.block_size) - 1 else torch.tensor([])
            labels = torch.cat((labels, next_data))

        if local_idx == (len(self.data) // self.block_size) - 1:
            self._next_shard()

        return inputs_ids, labels

In [25]:
dataset = ShardDataset(data_dir, block_size=block_size, split='train', process_rank=0, num_processes=2)

In [29]:
dataset[0][0].shape, dataset[0][1].shape

(torch.Size([450]), torch.Size([450]))

In [19]:




class ShardDataloader:
    def __init__(self, dataset: ShardDataset, batch_size=64, shuffle=True, pad=False):
        self.dataset = dataset
        self.batch_size = batch_size
        self.shuffle = shuffle
        self.pad = pad
        self.idxis = np.arange(len(self.dataset))

        if self.shuffle:
            np.random.shuffle(self.idxis)
        self.str_idx = 0

    def __iter__(self):
        self.str_idx = 0
        if self.shuffle:
            np.random.shuffle(self.idxis)
        return self

    def __next__(self):
        if self.str_idx >= len(self.idxis):
            raise StopIteration

        end_idx = min(self.str_idx + self.batch_size, len(self.idxis))
        batch_idxis = self.idxis[self.str_idx:end_idx]
        self.str_idx = end_idx

        batch = [self.dataset[i] for i in batch_idxis]
        inputs, labels = zip(*batch)
        inputs = stack(inputs)
        labels = stack(labels)

        if self.pad:
            inputs = pad_sequence(inputs, batch_first=True, padding_value=0)
            labels = pad_sequence(labels, batch_first=True, padding_value=-100)

        return inputs, labels

    def __len__(self):
        return len(self.dataset) // self.batch_size



In [31]:

if __name__ == "__main__":
    from torch.utils.data import DataLoader

    process_rank = 2
    num_processes = 3

    dataset = ShardDataset(
        data_dir= "/n/projects/kc2819/projects/ChotaLLM/data/wikitext2",
        block_size=128,
        split='train',
        process_rank=process_rank,
        num_processes=num_processes
    )

    print(f"Dataset length: {len(dataset)}")

    sampler = DistributedSampler(dataset, num_replicas=num_processes, rank=process_rank, shuffle=True)
    dataloader = DataLoader(dataset, batch_size=32, sampler=sampler, collate_fn=lambda x: tuple(zip(*x)))

    for batch_idx, (inputs, labels) in enumerate(dataloader):
        print(f"Process {process_rank} - Batch {batch_idx}: {inputs[0].shape}, {labels[0].shape}")

Dataset length: 6324
Process 2 - Batch 0: torch.Size([128]), torch.Size([128])
Process 2 - Batch 1: torch.Size([128]), torch.Size([128])
Process 2 - Batch 2: torch.Size([128]), torch.Size([128])
Process 2 - Batch 3: torch.Size([128]), torch.Size([128])
Process 2 - Batch 4: torch.Size([128]), torch.Size([128])
Process 2 - Batch 5: torch.Size([128]), torch.Size([128])
Process 2 - Batch 6: torch.Size([128]), torch.Size([128])
Process 2 - Batch 7: torch.Size([128]), torch.Size([128])
Process 2 - Batch 8: torch.Size([128]), torch.Size([128])
Process 2 - Batch 9: torch.Size([128]), torch.Size([128])
Process 2 - Batch 10: torch.Size([128]), torch.Size([128])
Process 2 - Batch 11: torch.Size([128]), torch.Size([128])
Process 2 - Batch 12: torch.Size([128]), torch.Size([128])
Process 2 - Batch 13: torch.Size([128]), torch.Size([128])
Process 2 - Batch 14: torch.Size([128]), torch.Size([128])
Process 2 - Batch 15: torch.Size([128]), torch.Size([128])
Process 2 - Batch 16: torch.Size([128]), torc

In [111]:
sampler.num_replicas

3

In [19]:
from torch import tensor, long, cat
import os

class ShardDatasets:

    def __init__(self,dataset_dir, block_size = 128, file_extension = '.npy', split = 'train'):
        self.dataset_dir = dataset_dir
        self.block_size = block_size
        self.file_extension = file_extension
        self.split = split

        self.shards = self._load_shards()
        self.current_shard_idx = 0
        self.data = self._load_data()

    def _load_shards(self):
        shards = [os.path.join(self.dataset_dir, f) for f in os.listdir(self.dataset_dir) if f.endswith(self.file_extension) and self.split in f]
        shards.sort()
        assert len(shards) > 0, f"No shards found in directory {self.dataset_dir} for split {self.split}."
        return shards

    def _load_data(self):
        if self.file_extension == '.npy':
            data = np.load(self.shards[self.current_shard_idx])
        else:
            raise NotImplementedError
        if data.dtype == np.int16:
            data = data.astype(np.int32)
        return  tensor(data, dtype=long)

    def _next_shard(self):
        self.current_shard_idx = (self.current_shard_idx + 1) % len(self.shards)
        self.data = self._load_data()

    def __len__(self):
        return sum(len(np.load(shard)) for shard in self.shards) // self.block_size # this is total number of blocks

    def __getitem__(self, idx):
        shard_size = len(self.data) // self.block_size
        while idx >= shard_size:
            idx -= shard_size
            self._next_shard()
            shard_size = len(self.data) // self.block_size

        start_idx = idx * self.block_size
        end_idx = start_idx + self.block_size if start_idx + self.block_size < len(self.data) else len(self.data)
        inputs_ids = self.data[start_idx:end_idx]
        labels = self.data[start_idx + 1:end_idx + 1]

        if len(labels) < self.block_size:
            labels = cat((labels, self.data[:self.block_size - len(labels)]))

        return inputs_ids, labels
    

        

In [20]:
data_dir = "/n/projects/kc2819/projects/ChotaLLM/data/wikitext2"
train_dataset = ShardDatasets(data_dir, block_size= block_size, split='train', file_extension='.npy')

In [24]:
len(train_dataset)

75893

## model

In [5]:
import torch
from torch import nn
from torch.nn import functional as F

In [6]:
# simple lookup table of index - num_embeddings with each index having embedding_dim vector representation
emb_layer = nn.Embedding(num_embeddings = 10, embedding_dim = 3) # vocab_size, embedding_size

print(emb_layer.weight.shape)

print(emb_layer.weight)

torch.Size([10, 3])
Parameter containing:
tensor([[ 1.1204, -0.1094, -1.1308],
        [ 0.3742,  0.3927,  0.4792],
        [-0.3982, -0.4998, -0.7896],
        [-0.4837,  0.4450,  0.4109],
        [-0.8308, -1.6025, -0.0689],
        [ 0.8746, -0.6552,  0.5417],
        [ 0.4448,  0.4127, -0.6123],
        [ 0.1343, -0.5025, -0.8294],
        [-1.9889, -0.1112,  0.2929],
        [-0.2769, -0.4240, -0.1411]], requires_grad=True)


In [7]:
input_indicies = torch.tensor([1,2,3])
map = emb_layer(input_indicies)
print(map)
print(map.shape)

tensor([[ 0.3742,  0.3927,  0.4792],
        [-0.3982, -0.4998, -0.7896],
        [-0.4837,  0.4450,  0.4109]], grad_fn=<EmbeddingBackward0>)
torch.Size([3, 3])


In [8]:
input_indicies = torch.tensor([[1,2,3],[4,5,6],[7,8,9]]) # batch of 3, with three tokens each
print(input_indicies.shape)
map = emb_layer(input_indicies)
print(map)
print(map.shape)                         

torch.Size([3, 3])
tensor([[[ 0.3742,  0.3927,  0.4792],
         [-0.3982, -0.4998, -0.7896],
         [-0.4837,  0.4450,  0.4109]],

        [[-0.8308, -1.6025, -0.0689],
         [ 0.8746, -0.6552,  0.5417],
         [ 0.4448,  0.4127, -0.6123]],

        [[ 0.1343, -0.5025, -0.8294],
         [-1.9889, -0.1112,  0.2929],
         [-0.2769, -0.4240, -0.1411]]], grad_fn=<EmbeddingBackward0>)
torch.Size([3, 3, 3])


In [13]:
# lets create the sentence to embedding for the model

sent_batch = [
    'hi how are you doing',
    'i am doing good',
]

tok_b = [tokenizer.encode(s) for s in sent_batch]
print(tok_b)

# lets pad the tokens
max_len = max([len(t) for t in tok_b])
print(max_len)

padded = [t + [0]*(max_len - len(t)) for t in tok_b]

print(padded)


input_tensor = torch.tensor(padded)
print(input_tensor)

[[50256, 5303, 703, 389, 345, 1804], [50256, 72, 716, 1804, 922]]
6
[[50256, 5303, 703, 389, 345, 1804], [50256, 72, 716, 1804, 922, 0]]
tensor([[50256,  5303,   703,   389,   345,  1804],
        [50256,    72,   716,  1804,   922,     0]])


In [48]:
class inputblock(nn.Module): # inherit the base class

    def __init__(self,vocab_size,block_size,embedding_size):
        super(inputblock, self).__init__()   ## always need to call this super constructor to initialize the base class
        self.tok_emb = nn.Embedding(vocab_size, embedding_size) # vocab_size * embedding_size look up table
        # back in the day we used to add sin and cos positional encodings here, but now we just use embeddings for that
        # this is because the model can learn the positional encodings as well
        self.pos_emb = nn.Embedding(block_size, embedding_size) 

    def forward(self, batch):

        """
        
        sentence: 'hi how are you doing' ---> | gpt2 encoding | ---> 50256(eot),  5303,   703,   389,   345,  1804 --> this token vector (batch)

        batch.shape = (B,T) ---> batch_size, block_size/context window

                  | -> token embedding - (B,T,C) lookup table                         |
        batch --> |                                                                   | -> pos + tok = (B,T,C) positional + token embeddings 
                  | -> positional embedding - (T,C) learnable positional embeddings   |                 positional embeddings casted to batch size
                  
        
        """
        B,C = batch.shape
        tok_emb = self.tok_emb(batch) # B,T,C
        pos = torch.arange(C).expand(B,C).to(batch.device)
        pos_emb = self.pos_emb(pos) # T,C
        return tok_emb + pos_emb    
    

In [49]:
B,T = input_tensor.shape
print(B,T)

2 6


In [50]:
i2tr = inputblock(vocab_size = tokenizer.get_vocab_size(), block_size = T, embedding_size = embedding_size)

out = i2tr(input_tensor)
print(out.shape) # B,T,C = 2, 6, 12

torch.Size([2, 6, 12])


In [72]:
class attentionhead(nn.Module):

    def __init__(self,emb_size,head_size):
        super(attentionhead, self).__init__()
        self.emb_size = emb_size
        self.head_size = head_size
        assert emb_size % head_size == 0, 'embedding size must be divisible by head size'

        # q,k,v embeddings 
        self.qkv = nn.Linear(emb_size, 3 * head_size,bias=False) # (B,T,hc) -> (B,T,hc) x 3              
        self.register_buffer('tril', torch.tril(torch.ones(emb_size,emb_size))) # lower triangular matrix

    def forward(self, x):
        B,T,C = x.size()
        q,k,v = self.qkv(x).split(self.head_size, dim = 2) # I have to split this properly at head_size to unpack 
                                                           # (B,T,hc) -> (B,T,hc) x 3 -> (B,T,hc) x 3
        
        # w = softmax(qk^T/sqrt(d_k))v
        w = q @ k.transpose(1,2) * (C ** -0.5) # (B,T,hc) x (B,hc,T) -> (B,T,T) 
        w = w.masked_fill(self.tril[:T,:T] == 0, float('-inf')) # mask the upper triangular matrix
        w = F.softmax(w,dim = 2) # (B,T,T)
        return w @ v # (B,T,T) x (B,T,hc) -> (B,T,hc)
    


class attensionblock(nn.Module):

    def __init__(self,emb_size,head_size):
        super(attensionblock, self).__init__()
        assert emb_size % head_size == 0, 'embedding size must be devisable by head size'
        self.head_size = head_size
        self.emb_size = emb_size
        self.n_heads = self.emb_size // self.head_size

        self.attention_heads = nn.ModuleList([attentionhead(emb_size,head_size) for _ in range(self.n_heads)])

        self.fc = nn.Linear(emb_size,emb_size)

    def forward(self,x):
        B,T,C = x.size()
        w = torch.cat([attn_head(x) for attn_head in self.attention_heads],dim = 2) # (B,T,hc) x n_heads -> (B,T,hc*n_heads)
        return self.fc(w) # (B,T,hc*n_heads) -> (B,T,C)
    

    

In [73]:
attn = attentionhead(emb_size = embedding_size, head_size = 4)
attn_out = attn(out)
print(attn_out.shape) # B,T,C = 2, 6, 12

attn_block = attensionblock(emb_size = embedding_size, head_size = 4)
attn_block_out = attn_block(out)
print(attn_block_out.shape) # B,T,C = 2, 6, 12

torch.Size([2, 6, 4])
torch.Size([2, 6, 12])
