### data 

In [1]:
import numpy as np


def load_data(npysplit):
    data = np.load(npysplit)
    return data

data_dir = "/n/projects/kc2819/projects/ChotaLLM/data/wikitext2"
trn_path, val_path, tst_path = data_dir + "/wikitext-2-raw-v1_train_000000.npy", data_dir + "/wikitext-2-raw-v1_validation_000000.npy", data_dir + "/wikitext-2-raw-v1_test_000000.npy"
train_data = load_data(trn_path)
valid_data = load_data(val_path)
test_data = load_data(tst_path)


print(f'number of tokens in train: {len(train_data)/10e6}M')
print(f'number of tokens in valid: {len(valid_data)/10e6}M')
print(f'number of tokens in test: {len(test_data)/10e6}M')

number of tokens in train: 0.01M
number of tokens in valid: 0.01M
number of tokens in test: 0.01M


In [2]:
train_data[:100], test_data[:100], valid_data[:100]

(array([50256, 50256,   796,   569, 18354,  7496, 17740,  6711,   796,
          220,   198, 50256, 50256,  2311,    73, 13090,   645,   569,
        18354,  7496,   513,  1058,   791, 47398, 17740,   357,  4960,
         1058, 10545,   230,    99,   161,   254,   112,  5641, 44444,
         9202, 25084, 24440, 12675, 11839,    18,   837,  6578,   764,
          569, 18354,  7496,   286,   262, 30193,   513,  1267,   837,
         8811,  6412,   284,   355,   569, 18354,  7496, 17740,  6711,
         2354,  2869,   837,   318,   257, 16106,  2597,  2488,    12,
           31,  2712,  2008,   983,  4166,   416, 29490,   290,  6343,
           13, 44206,   329,   262, 14047, 44685,   764, 28728,   287,
         3269,  2813,   287,  2869,   837,   340,   318,   262,  2368,
          983], dtype=uint16),
 array([50256, 50256,   796,  5199,   347,  2852,   353,   796,   220,
          198, 50256, 50256,  5199,   347,  2852,   353,   318,   281,
         3594,  2646,   837,  5581,   290, 214

In [3]:

import sys
sys.path.append("/n/projects/kc2819/projects/ChotaLLM")

from src.dataUtils import CustomDataset, CustomDataloader, customTokenizer

batch_size = 5
block_size = 32
embedding_size = 12

tokenizer = customTokenizer()

tokenizer.get_vocab_size()

50257

In [4]:
dir(get_encoding('gpt2'))

NameError: name 'get_encoding' is not defined

In [ ]:
seq = train_data[:1000]
print(tokenizer.decode_np(seq))

<|endoftext|><|endoftext|> = Valkyria Chronicles III = 
<|endoftext|><|endoftext|> Senjō no Valkyria 3 : Unrecorded Chronicles ( Japanese : 戦場のヴァルキュリア3 , lit . Valkyria of the Battlefield 3 ) , commonly referred to as Valkyria Chronicles III outside Japan , is a tactical role @-@ playing video game developed by Sega and Media.Vision for the PlayStation Portable . Released in January 2011 in Japan , it is the third game in the Valkyria series . Employing the same fusion of tactical and real @-@ time gameplay as its predecessors , the story runs parallel to the first game and follows the " Nameless " , a penal military unit serving the nation of Gallia during the Second Europan War who perform secret black operations and are pitted against the Imperial unit " Calamaty Raven " . 
<|endoftext|> The game began development in 2010 , carrying over a large portion of the work done on Valkyria Chronicles II . While it retained the standard features of the series , it also underwent multiple adj

In [ ]:
train_dataset = CustomDataset(trn_path, block_size= block_size)
valid_dataset = CustomDataset(val_path, block_size= block_size)
test_dataset = CustomDataset(tst_path, block_size= block_size)


In [ ]:
print(len(train_dataset), len(valid_dataset), len(test_dataset))
print(f'train', train_dataset[0],'\n', f'valid', valid_dataset[0],'\n', f'test', test_dataset[0])

3125 3125 3125
train (tensor([50256, 50256,   796,   569, 18354,  7496, 17740,  6711,   796,   220,
          198, 50256, 50256,  2311,    73, 13090,   645,   569, 18354,  7496,
          513,  1058,   791, 47398, 17740,   357,  4960,  1058, 10545,   230,
           99,   161]), tensor([50256,   796,   569, 18354,  7496, 17740,  6711,   796,   220,   198,
        50256, 50256,  2311,    73, 13090,   645,   569, 18354,  7496,   513,
         1058,   791, 47398, 17740,   357,  4960,  1058, 10545,   230,    99,
          161,   254])) 
 valid (tensor([50256, 50256,   796,  8074, 20272,  9106,  3876,   385,   796,   220,
          198, 50256, 50256,  8074, 20272,  9106,  3876,   385,   837,  1900,
          355,   262,  3427, 43657,   393,  2219, 43657,   837,   318,   257,
         4693,   286]), tensor([50256,   796,  8074, 20272,  9106,  3876,   385,   796,   220,   198,
        50256, 50256,  8074, 20272,  9106,  3876,   385,   837,  1900,   355,
          262,  3427, 43657,   393,  22

/n/projects/kc2819/projects/ChotaLLM/src/dataUtils.py:89: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  inputs_ids = tensor(inputs_ids,dtype = int64)
/n/projects/kc2819/projects/ChotaLLM/src/dataUtils.py:90: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels = tensor(labels,dtype = int64)


In [ ]:
# lets test the dataloaders
train_loader = CustomDataloader(train_dataset, batch_size=batch_size, shuffle=True)
valid_loader = CustomDataloader(valid_dataset, batch_size=batch_size, shuffle=True)
test_loader = CustomDataloader(test_dataset, batch_size=batch_size, shuffle=True)



In [ ]:
next(iter(train_loader)), next(iter(valid_loader)), next(iter(test_loader))

((tensor([[  764,  5501,  4843,   286,   262,  1492,   705,    82,  7110, 10069,
             257,  1180, 28953,   319,   262, 32022,  2066,   705,    82,  1964,
             290,  1919,  2858,   837,  1613,   290,  1944,   764,   220,   198,
           50256, 41969],
          [  837, 10807,   371,  9250,   373,  4137,   284,  1011,  1630,   286,
             262,  3074,   764,  1550,  3945,   718,   837,   339,  1908,   257,
            8766,  3512,   329, 16908,   286,   262, 24375,   284,  8599,   309,
            4728,   837],
          [  315,   292,   764,   220,   198, 50256, 11450,   837, 15987,   746,
            4910,   373,  8879,   416,  1194, 30529,    84,  2584,   272, 30968,
             837,   290,   788,   416, 30311, 37399,   378,   837,   508, 29209,
             340,   284],
          [  714,  5198,   284,   649,  1938,   981, 26645,   262,  6393,  6805,
             286,   262,  2168,   705, 11327,   764,   383, 15064,  3341,   547,
            3066,  2402,  1903,

In [ ]:

trn_batch = next(iter(train_loader))
print(trn_batch[0].shape, trn_batch[1].shape) # batch_size, block_size

tst_batch = next(iter(test_loader))
print(tst_batch[0].shape, tst_batch[1].shape)

val_batch = next(iter(valid_loader))
print(val_batch[0].shape, val_batch[1].shape)

torch.Size([5, 32]) torch.Size([5, 32])
torch.Size([5, 32]) torch.Size([5, 32])
torch.Size([5, 32]) torch.Size([5, 32])


## model

In [5]:
import torch
from torch import nn
from torch.nn import functional as F

In [6]:
# simple lookup table of index - num_embeddings with each index having embedding_dim vector representation
emb_layer = nn.Embedding(num_embeddings = 10, embedding_dim = 3) # vocab_size, embedding_size

print(emb_layer.weight.shape)

print(emb_layer.weight)

torch.Size([10, 3])
Parameter containing:
tensor([[ 1.1204, -0.1094, -1.1308],
        [ 0.3742,  0.3927,  0.4792],
        [-0.3982, -0.4998, -0.7896],
        [-0.4837,  0.4450,  0.4109],
        [-0.8308, -1.6025, -0.0689],
        [ 0.8746, -0.6552,  0.5417],
        [ 0.4448,  0.4127, -0.6123],
        [ 0.1343, -0.5025, -0.8294],
        [-1.9889, -0.1112,  0.2929],
        [-0.2769, -0.4240, -0.1411]], requires_grad=True)


In [7]:
input_indicies = torch.tensor([1,2,3])
map = emb_layer(input_indicies)
print(map)
print(map.shape)

tensor([[ 0.3742,  0.3927,  0.4792],
        [-0.3982, -0.4998, -0.7896],
        [-0.4837,  0.4450,  0.4109]], grad_fn=<EmbeddingBackward0>)
torch.Size([3, 3])


In [8]:
input_indicies = torch.tensor([[1,2,3],[4,5,6],[7,8,9]]) # batch of 3, with three tokens each
print(input_indicies.shape)
map = emb_layer(input_indicies)
print(map)
print(map.shape)                         

torch.Size([3, 3])
tensor([[[ 0.3742,  0.3927,  0.4792],
         [-0.3982, -0.4998, -0.7896],
         [-0.4837,  0.4450,  0.4109]],

        [[-0.8308, -1.6025, -0.0689],
         [ 0.8746, -0.6552,  0.5417],
         [ 0.4448,  0.4127, -0.6123]],

        [[ 0.1343, -0.5025, -0.8294],
         [-1.9889, -0.1112,  0.2929],
         [-0.2769, -0.4240, -0.1411]]], grad_fn=<EmbeddingBackward0>)
torch.Size([3, 3, 3])


In [13]:
# lets create the sentence to embedding for the model

sent_batch = [
    'hi how are you doing',
    'i am doing good',
]

tok_b = [tokenizer.encode(s) for s in sent_batch]
print(tok_b)

# lets pad the tokens
max_len = max([len(t) for t in tok_b])
print(max_len)

padded = [t + [0]*(max_len - len(t)) for t in tok_b]

print(padded)


input_tensor = torch.tensor(padded)
print(input_tensor)

[[50256, 5303, 703, 389, 345, 1804], [50256, 72, 716, 1804, 922]]
6
[[50256, 5303, 703, 389, 345, 1804], [50256, 72, 716, 1804, 922, 0]]
tensor([[50256,  5303,   703,   389,   345,  1804],
        [50256,    72,   716,  1804,   922,     0]])


In [48]:
class inputblock(nn.Module): # inherit the base class

    def __init__(self,vocab_size,block_size,embedding_size):
        super(inputblock, self).__init__()   ## always need to call this super constructor to initialize the base class
        self.tok_emb = nn.Embedding(vocab_size, embedding_size) # vocab_size * embedding_size look up table
        # back in the day we used to add sin and cos positional encodings here, but now we just use embeddings for that
        # this is because the model can learn the positional encodings as well
        self.pos_emb = nn.Embedding(block_size, embedding_size) 

    def forward(self, batch):

        """
        
        sentence: 'hi how are you doing' ---> | gpt2 encoding | ---> 50256(eot),  5303,   703,   389,   345,  1804 --> this token vector (batch)

        batch.shape = (B,T) ---> batch_size, block_size/context window

                  | -> token embedding - (B,T,C) lookup table                         |
        batch --> |                                                                   | -> pos + tok = (B,T,C) positional + token embeddings 
                  | -> positional embedding - (T,C) learnable positional embeddings   |                 positional embeddings casted to batch size
                  
        
        """
        B,C = batch.shape
        tok_emb = self.tok_emb(batch) # B,T,C
        pos = torch.arange(C).expand(B,C).to(batch.device)
        pos_emb = self.pos_emb(pos) # T,C
        return tok_emb + pos_emb    
    

In [49]:
B,T = input_tensor.shape
print(B,T)

2 6


In [50]:
i2tr = inputblock(vocab_size = tokenizer.get_vocab_size(), block_size = T, embedding_size = embedding_size)

out = i2tr(input_tensor)
print(out.shape) # B,T,C = 2, 6, 12

torch.Size([2, 6, 12])


In [72]:
class attentionhead(nn.Module):

    def __init__(self,emb_size,head_size):
        super(attentionhead, self).__init__()
        self.emb_size = emb_size
        self.head_size = head_size
        assert emb_size % head_size == 0, 'embedding size must be divisible by head size'

        # q,k,v embeddings 
        self.qkv = nn.Linear(emb_size, 3 * head_size,bias=False) # (B,T,hc) -> (B,T,hc) x 3              
        self.register_buffer('tril', torch.tril(torch.ones(emb_size,emb_size))) # lower triangular matrix

    def forward(self, x):
        B,T,C = x.size()
        q,k,v = self.qkv(x).split(self.head_size, dim = 2) # I have to split this properly at head_size to unpack 
                                                           # (B,T,hc) -> (B,T,hc) x 3 -> (B,T,hc) x 3
        
        # w = softmax(qk^T/sqrt(d_k))v
        w = q @ k.transpose(1,2) * (C ** -0.5) # (B,T,hc) x (B,hc,T) -> (B,T,T) 
        w = w.masked_fill(self.tril[:T,:T] == 0, float('-inf')) # mask the upper triangular matrix
        w = F.softmax(w,dim = 2) # (B,T,T)
        return w @ v # (B,T,T) x (B,T,hc) -> (B,T,hc)
    


class attensionblock(nn.Module):

    def __init__(self,emb_size,head_size):
        super(attensionblock, self).__init__()
        assert emb_size % head_size == 0, 'embedding size must be devisable by head size'
        self.head_size = head_size
        self.emb_size = emb_size
        self.n_heads = self.emb_size // self.head_size

        self.attention_heads = nn.ModuleList([attentionhead(emb_size,head_size) for _ in range(self.n_heads)])

        self.fc = nn.Linear(emb_size,emb_size)

    def forward(self,x):
        B,T,C = x.size()
        w = torch.cat([attn_head(x) for attn_head in self.attention_heads],dim = 2) # (B,T,hc) x n_heads -> (B,T,hc*n_heads)
        return self.fc(w) # (B,T,hc*n_heads) -> (B,T,C)
    

    

In [73]:
attn = attentionhead(emb_size = embedding_size, head_size = 4)
attn_out = attn(out)
print(attn_out.shape) # B,T,C = 2, 6, 12

attn_block = attensionblock(emb_size = embedding_size, head_size = 4)
attn_block_out = attn_block(out)
print(attn_block_out.shape) # B,T,C = 2, 6, 12

torch.Size([2, 6, 4])
torch.Size([2, 6, 12])
